# basic
title: Joao Lemos
subtitle: Frontend developer
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: http://7xrcp8.com1.z0.glb.clouddn.com/avatar.png
banner_small: http://7xrcp8.com1.z0.glb.clouddn.com/banner-small.png
banner_large: http://7xrcp8.com1.z0.glb.clouddn.com/banner-large.png

# disqus
disqus_shortname: jlemos

# social
social:
  github: https://github.com/joaolemos
  twitter: https://twitter.com/jnlemos
  linkedin : https://uk.linkedin.com/in/joaolemos
  stackoverflow: http://stackoverflow.com/cv/jlemos

# nav #
nav:
  home: .
  archive: archives
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
